# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{saucerly}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tim Riley"]
  s.date = %q{2009-09-25}
  s.email = %q{tim@openmonkey.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.md",
     "Rakefile",
     "TODO",
     "init.rb",
     "lib/pdf_helper.rb"
  ]
  s.homepage = %q{http://github.com/timriley/saucerly}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{PDF rending plugin for Rails using FlyingSaucer.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<flying_saucer>, [">= 0"])
    else
      s.add_dependency(%q<flying_saucer>, [">= 0"])
    end
  else
    s.add_dependency(%q<flying_saucer>, [">= 0"])
  end
end
